# Generated by Django 4.0.6 on 2022-08-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobileno',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Coffee'), ('SN', 'Snacks'), ('S', 'Shakes')], max_length=5),
        ),
    ]
